# Copyright (c) 2021 Cisco and/or its affiliates.
# 
# This software is licensed to you under the terms of the Cisco Sample
# Code License, Version 1.1 (the "License"). You may obtain a copy of the
# License at
# 
#                https://developer.cisco.com/docs/licenses
# 
# All use of the material herein must be in accordance with the terms of
# the License. All rights not expressly granted by the License are
# reserved. Unless required by applicable law or agreed to separately in
# writing, software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.
# 
# AUTHOR(s): Francisco Quiroz <frquiroz@cisco.com>

- name: Configure device
  hosts: nso
  connection: local
  gather_facts: no
  #no_log: true
 
  tasks:
  - name: Service variables in CSV file
    read_csv:
      path: l3vpn_client_vars.csv
    register: l3vpn
    delegate_to: localhost

  - name: Delete L3 VPN, XE
    nso_config:
      url: "{{ url }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      data:
        tailf-ncs:services:
          l3vpn:l3vpn_client:
          - client: "{{ item.client }}"
            client_id: "{{ item.client_id }}"
            site: "{{ item.site }}"
            __state: absent 
    loop: "{{ l3vpn.list }}"
    loop_control:
      label: "{{ item.device }}"       
    when: " item.tipo == 'iosxe'"

  - name: Delete L3 VPN, XR
    nso_config:
      url: "{{ url }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      data:
        tailf-ncs:services:
          l3vpn:l3vpn_client:
          - client: "{{ item.client }}"
            client_id: "{{ item.client_id }}"
            site: "{{ item.site }}"
            __state: absent 
    loop: "{{ l3vpn.list }}"
    loop_control:
      label: "{{ item.device }}"       
    when: " item.tipo == 'iosxr'"
